export enum Scopes {
  DEMO,
  CATEGORY
}

export const ActionTypes = {
  // COMMON
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  LOAD_LIST: 'LOAD_LIST',
  // DEMO
  DEMO_SET_ASYNC: 'DEMO_SET_ASYNC',
  DEMO_INCREMENT: 'DEMO_INCREMENT',
  DEMO_DECREMENT: 'DEMO_DECREMENT',
  // CATEGORY
  CT_LOAD_CATEGORIES: 'CT_LOAD_CATEGORIES'
}